### PR TITLE
Allow the user to move the third-person camera

### PR DESCRIPTION
**Pull request by clalancette**
This PR makes improvements to the third-person camera support that was merged in #20 .  In particular, it does the following two things:

1. It fixes a nasty bug where we were miscalculating the time between frames, meaning that the camera movement was much shakier than it was before.
2. It allows the user to move the camera while in third-person follow mode, and then will use that new fixed offset for the camera going forward.  This allows users to readjust where they are watching from.

In order to do the first thing, there is a slight revamp of the logic around `requestAnimationFrame` so that we get the timestamp at which the callback was started.

In my testing, with this and https://github.com/osrf/pounce-web/pull/14 applied, this works fairly well.  There is still a small bug where the camera is jerky the first few seconds after a camera move.  It fixes itself, but it is kind of ugly.  I'll look into that separately.

### CODE REVIEW

**Comment by german-e-mas** [comment]
I'm confused on how do we want the 3rd person camera to look like. Do we have any examples of what we are aiming for?

The camera is too jerky and I don't know how to position the camera. As soon as I leave the controls, it moves on its own to a position I don't intend to.

Also, the wheel zoom doesn't work, as it doesn't relies on clicks.

---

| Pan | Rotate | Zoom (Right-click) | Zoom (Wheel) |
| --- | --- | --- | --- |
| 3rdPersonCam-Pan | 3rdPersonCam-Rotate | 3rdPersonCam-ZoomRightClick | 3rdPersonCam-ZoomWheel |

**Comment by clalancette** [comment]
> The camera is too jerky

It should be much better than before this PR, but it could be tuned further.  I'm actually not entire sure how to do that, but I can play around with it.

> As soon as I leave the controls, it moves on its own to a position I don't intend to.

I don't think that is what is happening, even in your examples.  What happens is that in the last place you leave the camera when you let go of the mouse becomes the new offset for the camera.  That is applied during the next render cycle.  You are correct in that as soon as you release the mouse, it "snaps" to a weird position, but then it actually the moves from there to the position you intended.  This is the bug that I mentioned in my initial comment; I don't know why it is happening.

> Also, the wheel zoom doesn't work, as it doesn't relies on clicks.

Yes, I didn't implement the zoom for now.  I probably can with similar logic, though the scroll wheel works kind of weird in my testing; it does some combination of scrolling the browser window, and zooming in on the threejs scene.

**Comment by clalancette** [comment]
The latest code in 7565978 improves the situation here somewhat.  It should improve the bouncing a bit, and it should also make it so that the camera does less slewing around when changing positions.  It still doesn't completely fix the slewing around; there may be additional fixes needed.  But please take another look and see if this is somewhat better.

**Review by german-e-mas — APPROVED** [review]
Looks much better than before! I still think the camera isn't quite easy to control though, but that might be a personal opinion.

**Comment by clalancette** [comment]
> Looks much better than before! I still think the camera isn't quite easy to control though, but that might be a personal opinion.

No, I agree.  It isn't great.  But I think we should get this in as "something", and then maybe spend some time later one making it better.  I'm going to go ahead and merge this, thanks!

**Pull request merged**
