### PR TITLE
Add in first-person camera support.

### PR DESCRIPTION
**Pull request by clalancette**
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

### CODE REVIEW

**Review by german-e-mas — COMMENTED** [review]
Same as the third person camera, this requires the UI to call the `SceneManager`'s `firstPerson` method right?

**Comment by clalancette** [comment]
> Same as the third person camera, this requires the UI to call the `SceneManager`'s `firstPerson` method right?

Yes, exactly.  Thanks for reminding me, I forgot to open the PR to do that.  I'll do that now.

**Comment by clalancette** [comment]
And here's the pounce-web PR: https://github.com/osrf/pounce-web/pull/21

**Review by german-e-mas — APPROVED** [review]
Looks great!

**Comment by clalancette** [comment]
> Looks great!

Thanks!  Merging this one in.

**Pull request merged**
